TypeScriptEncoding: utf-8
PythonEncoding: utf-8
RustEncoding: utf-8
Item:
  - C:\rAthena\db\import\item_db.yml
  - C:\rAthena\db\re\item_db_equip.yml
  - C:\rAthena\db\re\item_db_usable.yml
  - C:\rAthena\db\re\item_db_etc.yml
ItemCombos:
  - C:\rAthena\db\import\item_combos.yml
  - C:\rAthena\db\re\item_combos.yml
Mob:
  - C:\rAthena\db\import\mob_db.yml
  - C:\rAthena\db\re\mob_db.yml
Skill:
  - C:\rAthena\db\import\skill_db.yml
  - C:\rAthena\db\re\skill_db.yml
DivinePrideKey: YourApiToken
SortOnInsert: true
SortOnUpdate: false
EnableFuzzyDivinePride: true
DivinePrideRangeSource: fuzzy
ShowComboComments: true
